id: OCM-SQS-Message
version: -1
name: OCM-SQS-Message
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d512bb6c-a92c-48d5-814d-523bb919a3c9
    type: start
    task:
      id: d512bb6c-a92c-48d5-814d-523bb919a3c9
      version: -1
      name: ""
      description: Playbook entry point.
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 6f06c9bc-28ef-485d-8025-67ef11658bf4
    type: regular
    task:
      id: 6f06c9bc-28ef-485d-8025-67ef11658bf4
      version: -1
      name: closeInvestigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 7dfe0765-7072-477f-8054-b9a21b0929d9
    type: title
    task:
      id: 7dfe0765-7072-477f-8054-b9a21b0929d9
      version: -1
      name: Playbook Finished
      description: Playbook end.
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: false
tests:
- No tests (auto formatted)
fromversion: 6.5.0
description: Generic playbook which just closes the incident.
