id: CE-OCM-Security
version: -1
name: CE-OCM-Security
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7bcdf18d-d6bf-4d0f-8af7-22a8356ae803
    type: start
    task:
      id: 7bcdf18d-d6bf-4d0f-8af7-22a8356ae803
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9bb7a920-767f-4c6f-8d0b-513e56c889b6
    type: regular
    task:
      id: 9bb7a920-767f-4c6f-8d0b-513e56c889b6
      version: -1
      name: Clear context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b095f31e-fd19-4c9e-8f26-b276b851b181
    type: title
    task:
      id: b095f31e-fd19-4c9e-8f26-b276b851b181
      version: -1
      name: Playbook Finished
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
tests:
- No tests (auto formatted)
fromversion: 6.5.0
description: Main case management playbook for the CleanEmail service
