id: CE-OCM-Security
version: -1
name: CE-OCM-Security
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4bdeadf1-0ee5-4f40-89b8-91c0a4590dc6
    type: start
    task:
      id: 4bdeadf1-0ee5-4f40-89b8-91c0a4590dc6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 222d349c-1bcd-41d1-806b-2d8663a9fb81
    type: regular
    task:
      id: 222d349c-1bcd-41d1-806b-2d8663a9fb81
      version: -1
      name: Clear context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "5"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: f5cf02b8-71c2-46f5-8ebc-2daee3718931
    type: title
    task:
      id: f5cf02b8-71c2-46f5-8ebc-2daee3718931
      version: -1
      name: Playbook Finished
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: e1debdd3-4f19-4227-8d14-ac2e484dcc61
    type: regular
    task:
      id: e1debdd3-4f19-4227-8d14-ac2e484dcc61
      version: -1
      name: Assign client
      description: Assigns a client from the service client list, using the incident source instance.
      scriptName: TC2TechCEAssignClient
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      clients:
        complex:
          root: lists
          accessor: clean_email_clients
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: b6750516-4a1a-4863-87ea-478beebf5b86
    type: regular
    task:
      id: b6750516-4a1a-4863-87ea-478beebf5b86
      version: -1
      name: Transcode client
      description: Get all rows matching the search parameters.
      script: CybPortalLists|||tc2tech-portal-rows-get
      type: regular
      iscommand: true
      brand: CybPortalLists
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      external_id:
        simple: trascoding
      filter:
        simple: "{\n\t\"and\": [\n\t\t{\n\t\t\t\"eq\": {\n\t\t\t\t\"attribute\": \"tenantID\",\n\t\t\t\t\"value\": ${incident.tc2techtenantid}\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"eq\": {\n\t\t\t\t\"attribute\": \"socID\",\n\t\t\t\t\"value\": ${incident.tc2techsocid}\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"eq\": {\n\t\t\t\t\"attribute\": \"clientID\",\n\t\t\t\t\"value\": ${incident.tc2techclientid}\n\t\t\t}\n\t\t}\n\t]\n}"
      limit:
        simple: "1"
      tenant_id:
        simple: "1"
      using:
        simple: CybPortalLists_PRO
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 744714a2-c211-41ba-8a63-8b0d53e5363d
    type: regular
    task:
      id: 744714a2-c211-41ba-8a63-8b0d53e5363d
      version: -1
      name: Generate UUID
      description: Generates a random UUID (UUID 4).
      scriptName: GenerateRandomUUID
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: cda9a259-d33f-42e8-8614-e2011004d77e
    type: regular
    task:
      id: cda9a259-d33f-42e8-8614-e2011004d77e
      version: -1
      name: Assign service IDs
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      tc2techserviceincidentid:
        complex:
          root: GeneratedUUID
      tc2techsourcesystemid:
        complex:
          root: lists
          accessor: services
          transformers:
          - operator: jmespath
            args:
              expression:
                value:
                  simple: clean_email.source_system_id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: false
tests:
- No tests (auto formatted)
fromversion: 6.5.0
description: Main case management playbook for the CleanEmail service
